config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'pages#home'

  get "automotive", to: "pages#automotive", as: "automotive"
  get "automotive_hurricane", to: "pages#automotive_hurricane", as: "automotive_hurricane"
  get "automotive_springdale", to: "pages#automotive_springdale", as: "automotive_springdale"
  get "automotive_st_george", to: "pages#automotive_st_george", as: "automotive_st_george"
  get "automotive_kanab", to: "pages#automotive_kanab", as: "automotive_kanab"

  get "blog", to: "pages#blog", as: "blog"
  get "commercial", to: "pages#commercial", as: "commercial"
  get "contact", to: "pages#contact", as: "contact"
  get "home", to: "pages#home", as: "home"
  get "residential", to: "pages#residential", as: "residential"
  get "reviews", to: "pages#reviews", as: "reviews"

  # Old Website
  get "stgeorge", to: "pages#automotive_st_george"
  get "StGeorge", to: "pages#automotive_st_george"
  get "hurricane", to: "pages#automotive_hurricane"
  get "Hurricane", to: "pages#automotive_hurricane"
  get "kanab", to: "pages#automotive_kanab"
  get "Kanab", to: "pages#automotive_kanab"
  get "springdale", to: "pages#automotive_springdale"
  get "SpringDale", to: "pages#automotive_springdale"
  get "Springdale", to: "pages#automotive_springdale"
  get "laverkin", to: "pages#automotive_hurricane"
  get "LaVerkin", to: "pages#automotive_hurricane"
  get "Laverkin", to: "pages#automotive_hurricane"

  put "contact_form", to: "pages#contact_form"

  get "admin_panel", to: "admin_panel#dashboard", as: "admin_panel"

  namespace :admin do
    resources :blog_posts
    resources :page_contents

    get "automotive", to: "pages#automotive"
    get "automotiveimages", to: "page_images#automotive"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog_post.rb
# == Schema Information
#
# Table name: blog_posts
#
#  id         :integer          not null, primary key
#  header     :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BlogPost < ApplicationRecord
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < AdminPanelController
  before_action :authenticate_admin!

  def index
    @blog_posts = BlogPost.all.order(created_at: "desc")
  end

  def new
    @blog_post = BlogPost.new
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def update
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.update_attributes(blog_post_params)
      flash[:notice] = "Blog Post successfully updated"
      redirect_to admin_blog_posts_path
    else
    end
  end

  def create
    @blog_post = BlogPost.create(blog_post_params)
    if @blog_post.valid?
      flash[:notice] = "Blog Post successfully created."
      redirect_to admin_blog_posts_path
    else
    end

  end

  def destroy
    BlogPost.find(params[:id]).destroy
    redirect_to admin_blog_posts_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:header, :body)
  end

end

app/views/admin/blog_posts/edit.html.erb
<% breadcrumb :edit_post, @blog_post %>

<%= form_for @blog_post, url: admin_blog_post_path(@blog_post), method: :put do |f| %>
  <div class="form-group">
    <%= f.label :header %>
    <%= f.text_field :header, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 20, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-default"%>
<% end %>

app/views/admin/blog_posts/index.html.erb
<% breadcrumb :posts %>

<%= link_to "Create New Post", new_admin_blog_post_path, class: "btn btn-default" %>

<table class="table table-striped">
  <tr>
    <th>Subject</th>
    <th></th>
  </tr>
  <% @blog_posts.each do |blog_post| %>
    <tr>
      <td>
        <%= blog_post.header %>
        <h3><%= blog_post.created_at.strftime("%B %-d, %Y") %></h3>
      </td>
      <td style="text-align: right; align: right;">
        <%= link_to edit_admin_blog_post_path(blog_post), class: "btn btn-default" do %>
          <span class="glyphicon glyphicon-edit" aria-hidden="true"> Edit</span>
        <% end %>
        <%= link_to(admin_blog_post_path(blog_post), {method: :delete, data: {confirm: "Are you sure you want to delete this Blog Post? This action cannot be undone"}, class: "btn btn-default"}) do %>
          <span class="glyphicon glyphicon-remove" aria-hidden="true"> Remove</span>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/blog_posts/new.html.erb
<% breadcrumb :new_post %>

<%= form_for @blog_post, url: admin_blog_posts_path, method: :post do |f| %>
  <div class="form-group">
    <%= f.label :header %>
    <%= f.text_field :header, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 20, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-default"%>

<% end %>