config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root 'pages#home'

  get "automotive", to: "pages#automotive", as: "automotive"
  get "automotive_hurricane", to: "pages#automotive_hurricane", as: "automotive_hurricane"
  get "automotive_springdale", to: "pages#automotive_springdale", as: "automotive_springdale"
  get "automotive_st_george", to: "pages#automotive_st_george", as: "automotive_st_george"
  get "automotive_kanab", to: "pages#automotive_kanab", as: "automotive_kanab"

  get "blog", to: "pages#blog", as: "blog"
  get "commercial", to: "pages#commercial", as: "commercial"
  get "contact", to: "pages#contact", as: "contact"
  get "home", to: "pages#home", as: "home"
  get "residential", to: "pages#residential", as: "residential"
  get "reviews", to: "pages#reviews", as: "reviews"

  # Old Website
  get "stgeorge", to: "pages#automotive_st_george"
  get "StGeorge", to: "pages#automotive_st_george"
  get "hurricane", to: "pages#automotive_hurricane"
  get "Hurricane", to: "pages#automotive_hurricane"
  get "kanab", to: "pages#automotive_kanab"
  get "Kanab", to: "pages#automotive_kanab"
  get "springdale", to: "pages#automotive_springdale"
  get "SpringDale", to: "pages#automotive_springdale"
  get "Springdale", to: "pages#automotive_springdale"
  get "laverkin", to: "pages#automotive_hurricane"
  get "LaVerkin", to: "pages#automotive_hurricane"
  get "Laverkin", to: "pages#automotive_hurricane"

  put "contact_form", to: "pages#contact_form"

  get "admin_panel", to: "admin_panel#dashboard", as: "admin_panel"

  namespace :admin do
    resources :blog_posts
    resources :page_contents

    get "automotive", to: "pages#automotive"
    get "automotiveimages", to: "page_images#automotive"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer-bottom">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span>
        <%= Time.now.year %> Copyright Jensen Locksmithing
      </div>

      <div class="footer-call col-md-offset-2 col-md-3">
        <a href="tel:435.319.0361">
          <i class="fa fa-phone-square"></i>
          <span>We're Available 24/7 - Call Now!</span>
        </a>
      </div>

      <div class="col-md-offset-2 col-md-2">
        <a href="https://twitter.com/jensenlocksmith" class="btn btn-social-icon btn-twitter">
          <span class="fa fa-twitter"></span>
        </a>

        <a href="https://plus.google.com/+Jensenlocksmithing" class="btn btn-social-icon btn-google">
          <span class="fa fa-google"></span>
        </a>

        <a href="https://www.facebook.com/Jensen-Locksmithing-260604310728891/" class="btn btn-social-icon btn-facebook">
          <span class="fa fa-facebook"></span>
        </a>

        <a href="https://www.youtube.com/c/jensenlocksmithing" class="btn btn-social-icon btn-google">
          <span class="fa fa-youtube-square"></span>
        </a>

      </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-mobile" aria-expanded="false">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag("logo.png", class: "locksmith-logo")%></a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-mobile">
      <ul class="nav navbar-nav" id="main-navbar">

        <!-- <li class="active"> -->
        <li>
          <%= link_to "Home", home_path %>
          <span class="sr-only">(current)</span>
        </li>

        <li>
          <%= link_to "Residential", residential_path %>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Automotive
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "General Automotive", automotive_path %>
            </li>

            <li role="separator" class="divider"></li>

            <li>
              <%= link_to "St. George | Washington", automotive_st_george_path %>
            </li>

            <li role="separator" class="divider"></li>

            <li>
              <%= link_to "Hurricane | La Verkin", automotive_hurricane_path %>
            </li>

            <li role="separator" class="divider"></li>

            <li>
              <%= link_to "Springdale | Zion National Park", automotive_springdale_path %>
            </li>

            <li role="separator" class="divider"></li>

            <li>
              <%= link_to "Kanab | And Surrounding Areas", automotive_kanab_path%>
            </li>
          </ul>
        </li>

        <li>
          <%= link_to "Commercial", commercial_path %>
        </li>

        <li>
          <%= link_to "Blog", blog_path %>
        </li>

        <li>
          <%= link_to "Reviews", "http://www.yelp.com/biz/jensen-locksmithing-la-verkin-3" %>
        </li>

        <li>
          <%= link_to "Contact Us", contact_path %>
        </li>

        <% if admin_signed_in? %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Dashboard", admin_panel_path %>
            </li>

            <li role="separator" class="divider"></li>

            <li>
              <%= link_to "Sign Out", destroy_admin_session_path, method: :delete  %>
            </li>
          </ul>
        </li>

        <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a class="call-us" href="tel:435.319.0361">Call Us: 435-319-0361</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Meta Gem -->
     <%= display_meta_tags site: 'Jensen Locksmithing' %>

    <!-- Google Tag Manager -->
    <% if Rails.env.production? %>
      <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-NX64VHJ');
      </script>
    <% end %>
    <!-- End Google Tag Manager -->

    <title>Jensen Locksmithing Serving St George, Ivins, Santa Clara, and Surrounding areas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>


    <% if Rails.env.production? %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-36125801-1', 'auto');
        ga('send', 'pageview');
      </script>
    <% end %>

  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
      <% if Rails.env.production? %>
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NX64VHJ"
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
      <% end %>
    <!-- End Google Tag Manager (noscript) -->
      <% if flash[:notice] %>
      <p class="bg-primary">
        <%= flash[:notice] %>
      </p>
    <% end %>

    <% if flash[:alert] %>
      <p class="bg-danger">
       <%= flash[:alert] %>
      </p>
    <% end %>

    <div class="app-container">
      <%= render "layouts/header" %>
      <% if admin_signed_in? %>
        <%= render "admin/layouts/admin_header" %>
      <% end %>
      <div class="page-container">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>